apiVersion: v2
name: prometheus-adapter
type: application
version: 0.1.0
dependencies:
  - name: "prometheus-adapter"
    version: 4.8.0
    repository: "https://prometheus-community.github.io/helm-charts"
