kind: Kustomization
namespace: monitoring
labels:
  - includeSelectors: true
    pairs:
      app: prometheus

resources:
- ingress.yaml
- prometheus.yaml
- rbac.yaml
- service.yaml
- servicemonitor.yaml
