---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgA4rwFmfARbrZsMX6sqocPpIsYU/ovtRcnaGugksDx7ya+zMf1mzSWUMdtGSodTewYEv0jQiHIkwALG1/NTtq9jBh/F2ahN/J019yCpzMpZXZF2eM8sauH3GsUSDow0ppJHNkcuFJB0V9clilEb1H230RBJabMKZ4z8RwfQbZ8GWtnU6d+pSiCNiIb+jOa1nMG/4RvjKHwDD8RQqECi0gs30AnxzWujQ3K9kTL4PQSFtmcw9aCMB+lSknc73AE56frHzAJsrh4zoMosoARLr1lUISGnQlexZImo1nPoBHUzwyhwlipQD/w0nJ6Dn3TKAAyco+wJEfotHFcmPjSGnlTzIWqz5+cisUdegiCKf5hXxLnOAJsVOeFC8/OlkfZchWNgwBIzoG1ctGEH+xSP7vVlMEzsRFFJL0iAkTSUnRNL7UKlFubSU69/acnvz2tQb4YdyYd56dBxDrOyvkGqQ07AgzECiLXElDrox7lvcLCYYJfokifoLMSGe12YbIVkLBjlLNkZ8UpR+JdGUActh3fcWbs9FnEwqs5PUhOF9o4gWEqbPXLZh8bFKVR3Tt4/sM+Iwyi5rFHemy0vxACsW5n25CPV7LY8ZYKbJMM/XtfESKj+aC8kGDAq4L5aOBIzrfxe46fdTWEnANGB8IFf7v8KAoWhiPplTmEwd2Z5L3RxrNwKCrJqq8CkXBzYkDP0WN8dBptPYAjXxEKEm1SajCzQyuQn/9EVxFAyxreb7E4MUemEy7M=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
