---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAZNhgTf3zgMo02zwAwZmj78nr7QCPFnnyK0JXjMH29DXclCn43Nh8Ro+jQKnm0/IQLN0WbOoH/MtpwtBxRs0xJ3NJNiwt2UkYEAfRr5MiXs4M1HMCHdNurQRhI797i0Ws1zimJBeBkZhNal0HB0onYAikNfNiqHLUzGc4CWNeNynpHDKWRRyirOTajcDBDoikWgKFiRb1Mw5TIO84aXYXF1zQ4vkcvaauOgehJO8DvI5G67vnu4inmkLm1IEhHN3hARQ5ls3CYXf4TKd/CNPQI0Cc6F+MzqtNdwSxJZz3IexEFlqwQNLjwIsp4yYGgUlW0+3hYHXysZg7rdpecA82QrvK43BHNDSa6wjArjQjwGMCSe6c630doTU8BaGRMxzdK+PGj18LSURllKbS6MMyf87+N8qllfoSioyc0s7RFPeoyfsqqv4k0U+QJn3P42yvq88ZIPHqj0k0mtaW55Tkhv2F/Iwn1Q49HUm9IJcemeMF+6a8SVwWKL75L9X5IjhFtIjFINqFZmmOZ5ZZqiM6N+sE/+dZ7wNIsxObaGWr9RJhXaKraEBRb3Xe7xw0lI6duk0q/lxdy9Olt0nwNXoEJdn250RtFxh1XSJHEtqXi3tJLmA2mrysi3vK5gbQL3pYoWd/sGHrSTw30ZqnT+tuu6mc+YCGZjP9JwlyXzwaTRMMDSpHW9P3Oih86JXw7orhqf/y3Mlenuy2kjsOFKV83gR3thtTZVAN5e/Db2w5+hi7ZLz8=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
