apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeb17-internal
  namespace: traefik
spec:
  secretName: wildcard-zeb17-internal
  dnsNames:
  - "zeb17-int.duckdns.org"
  - "*.zeb17-int.duckdns.org"
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    group: cert-manager.io
    kind: ClusterIssuer
