apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prometheus-adapter-dev
spec:
  subscriptions:
    warehouse: prometheus-adapter
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/zbialik/homelab.git
      readBranch: main
      writeBranch: main
      helm:
        charts:
        - chartPath: k8s/helm/test/prometheus-adapter
          name: prometheus-adapter
          registryURL: https://prometheus-community.github.io/helm-charts
    argoCDAppUpdates:
    - appName: prometheus-adapter
      appNamespace: argocd
