kind: Kustomization
namespace: fantrax-pl-team-manager
labels:
- includeSelectors: true
  pairs:
    app: fantrax-pl-team-manager

resources:
- deploy.yaml
- sealed-fantrax-cookie.yaml

images:
- name: zach17/fantrax-pl-team-manager
  newTag: v1.2.2
