---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: odds-api-key
  namespace: fantrax-pl-team-manager
spec:
  encryptedData:
    odds-api-key: AgBteCzAJrqVDVgmV54i7Okypy1EXpbyST33NzHBU3t+9Or6mF2YetV7TPcOs3RX+Wtk+lgWA8w9xK7rkdR8xXxVOuZr36sT2Q9Iia0Hg1ATORirc8hR4NDJKlU0ogC65JypjogVLStPWFCDurQyAhwEgjkOdwRdgRWScgTuo03M5sjHDVuj7QkLI2rv2ihuA0C0pnhm8xH4xJPAEw25pKH0j2QeVPu0/pmia/BflM/vdISx/y3yEhjIXya86U4rZsUxoxlAWv35xAJZIeHLp89chaJoImz7azcd9fOtblNnQGGjwOCy3SLc1b4Z1voF0NA8CjFAjtyy6gHHjEvQ/5SvHvAP4F/ANuUfBIHmJWUwv2u767fmTeBPekyGAcmCKR92zY2CNxFFnxOc3llJqyiwjh0J4Z4+m84+1qb92U7/PtDi98UtOz95ZGUjhB8INqmkNnhfaaYCg0J1x8W4w+Tkq72tA/dBzKRpxhBMW59Vd7fQHyXWKCnCGlsGfoh8iQGuxL1PaU9Zt8DAr2dee2bet+vh7Jy6UHU4vbwwVBjptwIpAunB3OpPF+taQ7anoX+CrCVU5KJNnfMJKMQqqq0gkp2SG4oy+JgW/lESHNZSvYvZmovbXuCLCr8aEcRRMtIkjKX7ZqOyMq7Sxjc+xiZwLh9lEEFtxupy5eot1prxGJwLWGmBniVoTLgEq/AoJ24qXAY7d0UJF3i7dyzWKSC4HdjYpU6U9xHigLC9ovNBtg==
  template:
    metadata:
      creationTimestamp: null
      name: odds-api-key
      namespace: fantrax-pl-team-manager
