apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: fantrax-pl-team-manager
  name: fantrax-pl-team-manager
  namespace: fantrax-pl-team-manager
spec:
  serviceName: fantrax-pl-team-manager
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fantrax-pl-team-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fantrax-pl-team-manager
    spec:
      containers:
      - image: zach17/fantrax-pl-team-manager:placeholder
        command:
        - python
        - -m
        - fantrax_pl_team_manager
        - --persist-odds-data
        name: fantrax-pl-team-manager
        imagePullPolicy: IfNotPresent
        env:
        - name: LEAGUE_ID
          value: "o90qdw15mc719reh"
        - name: TEAM_ID
          value: "jassfpe6mc719rep"
        - name: COOKIE_PATH
          value: "/app/deploy/fantraxloggedin.cookie"
        - name: THE_ODDS_API_KEY
          valueFrom:
            secretKeyRef:
              name: odds-api-key
              key: odds-api-key
        volumeMounts:
        - name: cookie-secret
          mountPath: /app/deploy
          readOnly: true
        - name: data
          mountPath: /app/data
      volumes:
      - name: cookie-secret
        secret:
          secretName: fantrax-cookie
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi