tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-zeb17-internal

certificatesResolvers:
  default:
    acme:
      email: "zachary.e.bialik@gmail.com"
      storage: "/data/acme.json"
      httpChallenge:
        entryPoint: "web"
