apiVersion: v2
name: node-exporter
type: application
version: 0.1.0
dependencies:
  - name: "prometheus-node-exporter"
    version: "4.23.0"
    repository: "https://prometheus-community.github.io/helm-charts"
