kind: Kustomization
namespace: kube-system
commonLabels:
  app.zb/name: kube-state-metrics

resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- servicemonitor.yaml

images:
- name: kube-state-metrics
  newName: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.10.0
